// twtheme.idl : IDL source for twtheme
//

// This file will be processed by the MIDL tool to
// produce the type library (twtheme.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "..\model-libs\objmdl\objmdl_contract_i.idl";
import "..\model-libs\viewmdl\viewmdl_contract_i.idl";
import "..\twitter\twitter_contract_i.idl";

typedef enum ElementType
{
	UnknownValue,
	HorizontalContainer,
	ImageColumn,
	TextColumn,
	MarqueeProgressColumn
} ElementType;

[
	object,
	uuid(A8F6F50C-7E27-4472-8A3F-091EE6EB747C),
	pointer_default(unique)
]
interface ILayoutBuilder : IUnknown
{
	HRESULT SetColorMap(IThemeColorMap* pThemeColorMap);
	HRESULT SetFontMap(IThemeFontMap* pThemeFontMap);
	HRESULT BuildLayout(HDC hdc, RECT* pSourceRect, IVariantObject* pLayoutObject, IVariantObject* pValueObject, IImageManagerService* pImageManagerService, IColumnsInfo* pColumnInfo);
};

[
	object,
	uuid(367EB80B-2080-4C46-BABE-D52AF3F5D210),
	pointer_default(unique)
]
interface ILayoutPainter : IUnknown
{
	HRESULT SetColorMap(IThemeColorMap* pThemeColorMap);
	HRESULT SetFontMap(IThemeFontMap* pThemeFontMap);
	HRESULT EraseBackground(HDC hdc, IColumnsInfo* pColumnInfo);
	HRESULT PaintLayout(HDC hdc, POINT* ptOrigin, IImageManagerService* pImageManagerService, IColumnsInfo* pColumnInfo, BSTR bstrItemName);
};

[
	object,
	uuid(BEC4D679-8B74-41BC-8F6E-510F85A1F202),
	pointer_default(unique)
]
interface ILayoutManagerInternal : IUnknown
{
	HRESULT SetColorMap(IThemeColorMap* pThemeColorMap);
	HRESULT SetFontMap(IThemeFontMap* pThemeFontMap);
};

[
	uuid(F7BFC6EF-D8BE-4C1A-A9D5-9FC57D58BF5C),
	version(1.0),
]
library twthemeLib
{
	importlib("stdole2.tlb");
	[
		uuid(6EA78630-DC6D-4D2B-91F0-686B260F29D6)
	]
	coclass PluginTable
	{
		[default] interface IPluginTable;
	};
	[
		uuid(B682B92C-ACB3-446D-A37D-E11C901385CA)
	]
	coclass SkinTimeline
	{
		[default] interface ISkinTimeline;
	};
	[
		uuid(41F33BEE-3D82-4173-9F5E-79C91523843B)
	]
	coclass ThemeColorMap
	{
		[default] interface IThemeColorMap;
	};
	[
		uuid(986AF532-E457-4A2D-894D-0805AB6BD0B1)
	]
	coclass ThemeFontMap
	{
		[default] interface IThemeFontMap;
	};
	[
		uuid(A4B1D02D-648F-4D71-9907-7B84B9DF2422)
	]
	coclass SkinTabControl
	{
		[default] interface ISkinTabControl;
	};
	[
		uuid(D9BF55FB-091B-4858-82EC-EBD0137D04FB)
	]
	coclass SkinCommonControl
	{
		[default] interface ISkinCommonControl;
	};
	[
		uuid(0B2EE239-BF11-41FF-8DF0-525232084378)
	]
	coclass SkinUserAccountControl
	{
		[default] interface ISkinUserAccountControl;
	};
	[
		uuid(A7C215DD-BB09-4045-9029-9EE9D1D0A389)
	]
	coclass ThemeDefault
	{
		[default] interface ITheme;
	};
	[
		uuid(CEE6C71C-CA9F-4BE3-AA49-66F379D9F266)
	]
	coclass LayoutManager
	{
		[default] interface ILayoutManager;
	};
	[
		uuid(B086CC3E-137A-4136-A2B9-92E1FB5BB267)
	]
	coclass LayoutBuilder
	{
		[default] interface ILayoutBuilder;
	};
	[
		uuid(A158CE43-161C-44E5-A88C-D51BCBBB0309)
	]
	coclass LayoutPainter
	{
		[default] interface ILayoutPainter;
	}; 
};

