#pragma once

#define WM_TWVIEW_FIRST_MSG WM_TWIITER_FIRST_MSG + 1
#define WM_UPDATE_VIEW_CONTROL WM_TWVIEW_FIRST_MSG + 1
#define WM_PLAYER_STARTED WM_TWVIEW_FIRST_MSG + 2
#define WM_PLAYER_PLAY WM_TWVIEW_FIRST_MSG + 3
#define WM_PLAYER_CLOSE WM_TWVIEW_FIRST_MSG + 4
#define WM_TWVIEW_LAST_MSG WM_TWIITER_FIRST_MSG + 100
