#pragma once

#ifndef __TWITCONN__
DEFINE_GUID(CLSID_TwitterConnection, 0x20841FB0, 0x9F07, 0x4DA6, 0xA8, 0x78, 0x41, 0x92, 0x1C, 0x82, 0xC4, 0x40);
#endif

#define VAR_TWITTER_USER_OBJECT L"VAR_TWITTER_USER_OBJECT"
#define VAR_TWITTER_USER_DISPLAY_NAME L"VAR_TWITTER_USER_DISPLAY_NAME"
#define VAR_TWITTER_USER_NAME L"VAR_TWITTER_USER_NAME"
#define VAR_TWITTER_USER_IMAGE L"VAR_TWITTER_USER_IMAGE"
#define VAR_TWITTER_USER_BACKCOLOR L"VAR_TWITTER_USER_BACKCOLOR"
#define VAR_TWITTER_USER_FORECOLOR L"VAR_TWITTER_USER_FORECOLOR"
#define VAR_TWITTER_USER_BANNER L"VAR_TWITTER_USER_BANNER"
#define VAR_TWITTER_USER_FOLLOWERS_COUNT L"VAR_TWITTER_USER_FOLLOWERS_COUNT"
#define VAR_TWITTER_USER_FRIENDS_COUNT L"VAR_TWITTER_USER_FRIENDS_COUNT"
#define VAR_TWITTER_USER_TWEETS_COUNT L"VAR_TWITTER_USER_TWEETS_COUNT"
#define VAR_TWITTER_USER_DESCRIPTION L"VAR_TWITTER_USER_DESCRIPTION"

#define VAR_TWITTER_IMAGE L"VAR_TWITTER_IMAGE"
#define VAR_TWITTER_TEXT L"VAR_TWITTER_TEXT"
#define VAR_TWITTER_NORMALIZED_TEXT L"VAR_TWITTER_NORMALIZED_TEXT"
#define VAR_TWITTER_URL L"VAR_TWITTER_URL"
#define VAR_TWITTER_MEDIAURL L"VAR_TWITTER_MEDIAURL"
#define VAR_TWITTER_MEDIAURL_SHORT L"VAR_TWITTER_MEDIAURL_SHORT"
#define VAR_TWITTER_MEDIAURL_THUMB L"VAR_TWITTER_MEDIAURL_THUMB"
#define VAR_TWITTER_MEDIAURLS L"VAR_TWITTER_MEDIAURLS"
#define VAR_TWITTER_URLS L"VAR_TWITTER_URLS"
#define VAR_TWITTER_CREATED_AT L"VAR_TWITTER_CREATED_AT"
#define VAR_TWITTER_RETWEETED_USER_DISPLAY_NAME L"VAR_TWITTER_RETWEETED_USER_DISPLAY_NAME"
#define VAR_TWITTER_RETWEETED_USER_NAME L"VAR_TWITTER_RETWEETED_USER_NAME"
#define VAR_TWITTER_IN_REPLYTO_STATUS_ID L"VAR_TWITTER_IN_REPLYTO_STATUS_ID"
#define VAR_TWITTER_ORIGINAL_ID L"VAR_TWITTER_ORIGINAL_ID"

#define VAR_TWITTER_USER_DISPLAY_NAME_USER_ACCOUNT L"VAR_TWITTER_USER_DISPLAY_NAME_USER_ACCOUNT"

#define VAR_TWITTER_DELIMITER L"VAR_TWITTER_DELIMITER"

#define VAR_TEXT L"VAR_TEXT"
#define VAR_VALUE L"VAR_VALUE"
#define VAR_IS_URL L"VAR_IS_URL"
#define VAR_IS_IMAGE L"VAR_IS_IMAGE"
#define VAR_IS_WORDWRAP L"VAR_IS_WORDWRAP"
#define VAR_MAX_ID L"VAR_MAX_ID"
#define VAR_SINCE_ID L"VAR_SINCE_ID"

#define TYPE_TWITTER_OBJECT L"TYPE_TWITTER_OBJECT"