#pragma once

#ifndef __TWITCONN__
DEFINE_GUID(CLSID_TwitterConnection, 0x20841FB0, 0x9F07, 0x4DA6, 0xA8, 0x78, 0x41, 0x92, 0x1C, 0x82, 0xC4, 0x40);
#endif

#define VAR_TWITTER_USER_DISPLAY_NAME L"VAR_TWITTER_USER_DISPLAY_NAME"
#define VAR_TWITTER_USER_NAME L"VAR_TWITTER_USER_NAME"
#define VAR_TWITTER_USER_IMAGE L"VAR_TWITTER_USER_IMAGE"
#define VAR_TWITTER_TEXT L"VAR_TWITTER_TEXT"
#define VAR_TWITTER_NORMALIZED_TEXT L"VAR_TWITTER_NORMALIZED_TEXT"
#define VAR_TWITTER_URL L"VAR_TWITTER_URL"
#define VAR_TWITTER_URLS L"VAR_TWITTER_URLS"
#define VAR_TWITTER_CREATED_AT L"VAR_TWITTER_CREATED_AT"
#define VAR_TWITTER_RETWEETED_USER_DISPLAY_NAME L"VAR_TWITTER_RETWEETED_USER_DISPLAY_NAME"
#define VAR_TWITTER_RETWEETED_USER_NAME L"VAR_TWITTER_RETWEETED_USER_NAME"

#define VAR_TWITTER_DELIMITER L"VAR_TWITTER_DELIMITER"

#define VAR_TEXT L"VAR_TEXT"
#define VAR_VALUE L"VAR_VALUE"
#define VAR_IS_URL L"VAR_IS_URL"
#define VAR_IS_IMAGE L"VAR_IS_IMAGE"
#define VAR_IS_WORDWRAP L"VAR_IS_WORDWRAP"