// twiconn.idl : IDL source for twiconn
//

// This file will be processed by the MIDL tool to
// produce the type library (twiconn.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "twitconn_contract_i.idl";
import "..\model-libs\ObjMdl\objmdl_contract_i.idl";

[
	uuid(7622A306-6AF6-4D18-AC9F-A685EAD09458),
	version(1.0),
]
library twiconnLib
{
	importlib("stdole2.tlb");
	[
		uuid(20841FB0-9F07-4DA6-A878-41921C82C440)		
	]
	coclass TwitterConnection
	{
		[default] interface ITwitterConnection;
	};
	[
		uuid(486001AF-C13C-4BDC-A0CA-BA493B3BF106)
	]
	coclass TwitterStreamingConnection
	{
		[default] interface ITwitterStreamingConnection;
	};
	[
		uuid(6EA78630-DC6D-4D2B-91F0-686B260F29D6)
	]
	coclass PluginTable
	{
		[default] interface IPluginTable;
	};
};

import "shobjidl.idl";
