// This file will be processed by the MIDL tool to
// produce the type library (twiconn.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "objmdl_contract_i.idl";

[
	object,
	uuid(68F938F0-575F-448A-A735-1F7A6EF0D8F3),
	pointer_default(unique)
]
interface ITwitterConnection : IUnknown
{
	HRESULT GetAccessUrl(BSTR bstrUser, BSTR bstrPass, BSTR* pbstrAuthKey, BSTR* pbstrAuthSecret, BSTR* pbstrUrl);
	HRESULT GetAccessTokens(BSTR bstrUser, BSTR bstrPass, BSTR bstrAuthKey, BSTR bstrAuthSecret, BSTR bstrPin, BSTR* pbstrKey, BSTR* pbstrKeySecret);
	HRESULT OpenConnection(BSTR bstrKey, BSTR bstrSecret);
	HRESULT OpenConnectionWithAppAuth();
	HRESULT GetTimeline(BSTR bstrUserId, BSTR bstrMaxId, BSTR bstrSinceId, UINT uiMaxCount, IObjArray** ppObjectArray);
	HRESULT GetTwit(BSTR bstrId, IVariantObject** ppVariantObject);
	HRESULT Search(BSTR bstrQuery, BSTR bstrSinceId, UINT uiCount, IObjArray** ppObjectArray);
	HRESULT FollowUser(BSTR bstrUserName);
	HRESULT UnfollowUser(BSTR bstrUserName);
	HRESULT GetLists(IObjArray** ppObjectArray);
	HRESULT GetListTweets(BSTR bstrListId, UINT uiCount, IObjArray** ppObjectArray);
	HRESULT GetUserSettings(IVariantObject** ppVariantObject);
	HRESULT GetFollowStatus(BSTR bstrTargetUserName, BOOL* pbFollowing);
};

[
	object,
	uuid(2B3A4708-9EDF-4240-A151-A47A5F317B4C),
	pointer_default(unique)
]
interface ITwitterStreamingConnection : IUnknown
{
	HRESULT StartStream(BSTR bstrKey, BSTR bstrSecret);
	HRESULT StopStream();
};

[
	object,
	uuid(0DBBC2C9-EC68-4CFE-AABA-E0BD094E0626),
	pointer_default(unique)
]
interface ITwitterStreamingConnectionEventSink : IUnknown
{
	HRESULT OnMessages(IObjArray* pObjectArray);
};
