// twitter.idl : IDL source for twitter
//

// This file will be processed by the MIDL tool to
// produce the type library (twitter.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "..\ObjMdl\objmdl_contract_i.idl";
import "..\ViewMdl\viewmdl_contract_i.idl";

typedef struct TtagDRAWITEMSTRUCT {
	UINT        CtlType;
	UINT        CtlID;
	UINT        itemID;
	UINT        itemAction;
	UINT        itemState;
	HWND        hwndItem;
	HDC         hDC;
	RECT        rcItem;
	ULONG_PTR   itemData;
} TDRAWITEMSTRUCT;

typedef struct TtagMEASUREITEMSTRUCT {
	UINT       CtlType;
	UINT       CtlID;
	UINT       itemID;
	UINT       itemWidth;
	UINT       itemHeight;
	ULONG_PTR  itemData;
} TMEASUREITEMSTRUCT;

[
	object,
	uuid(DC001682-90CC-497F-BCE6-D00D712FD241),
	pointer_default(unique)
]
interface IFormsService : IUnknown
{
};

[
	object,
	uuid(03F5DD74-E610-409A-991F-20BDDBA9A625),
	pointer_default(unique)
]
interface ITimelineService : IUnknown
{
};

[
	object,
	uuid(27812A7C-A85F-4184-B1DA-7E9EA55B5816),
	pointer_default(unique)
]
interface IViewControllerService : IUnknown
{
};

[
	object,
	uuid(627BE6CD-5CB1-4364-817A-1EABA04B52C9),
	pointer_default(unique)
]
interface IThemeColorMap : IUnknown
{
	HRESULT GetColor(BSTR bstrColorName, DWORD* dwColor);
	HRESULT SetColor(BSTR bstrColorName, DWORD dwColor);
};

[
	object,
	uuid(DD372332-232D-4CA9-9807-B2F21D3C689A),
	pointer_default(unique)
]
interface IThemeFontMap : IUnknown
{
	HRESULT GetFont(BSTR bstrFontName, HFONT* phFont);
	HRESULT SetFont(BSTR bstrFontName, BSTR bstrFontFamily, DWORD dwSize, BOOL bBold, BOOL bUnderline);
};

[
	object,
	uuid(2EC751CC-D4F3-4B3B-B0C7-862916A085FC),
	pointer_default(unique),
	local
]
interface IColumnRects : IUnknown
{
	HRESULT AddRect(RECT rect, UINT* puiIndex);
	HRESULT GetRect(UINT uiIndex, RECT* rect);
	HRESULT GetCount(UINT* puiCount);
	HRESULT Clear();
	HRESULT SetRectProp(UINT uiIndex, BSTR bstrKey, BSTR bstrValue);
	HRESULT GetRectProp(UINT uiIndex, BSTR bstrKey, BSTR* bstrValue);
};

[
	object,
	uuid(CAE8EE20-A39A-4677-A9C0-FDD8D3D7015E),
	pointer_default(unique),
	local
]
interface ISkinTimeline : IUnknown
{
	HRESULT SetColorMap(IThemeColorMap* pThemeColorMap);
	HRESULT SetFontMap(IThemeFontMap* pThemeFontMap);
	HRESULT DrawItem(HWND hwndControl, IColumnRects* pColumnRects, TDRAWITEMSTRUCT* lpdi, int iHoveredItem, int iHoveredColumn);
	HRESULT MeasureItem(HWND hwndControl, IVariantObject* pItemObject, TMEASUREITEMSTRUCT* lpMeasureItemStruct, IColumnRects* pColumnRects);
};

[
	object,
	uuid(304C4130-701C-4951-AF30-2A38A0A51D31),
	pointer_default(unique)
]
interface ITimelineControl : IControl2
{
	HRESULT SetItems(IObjArray* pObjectArray);
	HRESULT SetSkinTimeline(ISkinTimeline* pSkinTimeline);
};

[
	object,
	uuid(825B6027-F439-4586-8DAE-DF9AE8527ABD),
	pointer_default(unique)
]
interface ITheme : IUnknown
{
	HRESULT SetColorMap(IThemeColorMap* pThemeColorMap);
	HRESULT GetTimelineSkin(ISkinTimeline** ppSkinTimeline);
};

[
	object,
	uuid(3A2E1784-55A2-4075-8617-2253A70762FF),
	pointer_default(unique)
]
interface IThemeService : IUnknown
{
	HRESULT AddColorMap(GUID gThemeId, IThemeColorMap* pThemeColorMap);
	HRESULT RemoveColorMap(GUID gThemeId);

	HRESULT AddTheme(GUID gThemeId, ITheme* pTheme);
	HRESULT RemoveTheme(GUID gThemeId);

	HRESULT GetThemes(IObjArray** ppObjectArray);
	HRESULT ApplyTheme(GUID gId);

	HRESULT ApplyThemeFromSettings();
};

[
	object,
	uuid(924BA62A-74BF-463A-8008-497B241FC448),
	pointer_default(unique)
]
interface IOpenUrlService : IUnknown
{
	HRESULT OpenColumnAsUrl(BSTR bstrColumnName, DWORD dwColumnIndex, IColumnRects* pColumnRects, IVariantObject* pVariantObject);
};

[
	uuid(12BF3C97-9ACD-43C3-9E73-698AF2DAE645),
	version(1.0),
]
library twitterLib
{
	importlib("stdole2.tlb");

	[
		uuid(6EA78630-DC6D-4D2B-91F0-686B260F29D6)
	]
	coclass PluginTable
	{
		[default] interface IPluginTable;
	};
	[
		uuid(75E49C09-05E4-4643-983F-624DC073535A)		
	]
	coclass TimelineControl
	{
		[default] interface ITimelineControl;
	};
	[
		uuid(5BEE1835-5D53-48C0-AB58-05EC1513010F)		
	]
	coclass FormsService
	{
		[default] interface IFormsService;
	};
	[
		uuid(6AFA6FA2-12D6-450E-AEFF-60B66F8B7574)
	]
	coclass SettingsControl
	{
		[default] interface IControl;
	};
	[
		uuid(FB68EE85-7555-407C-BECA-64406C74F1BC)		
	]
	coclass TimelineService
	{
		[default] interface ITimelineService;
	};
	[
		uuid(A31AF0A5-BE10-46FE-974F-55E0AA68070D)		
	]
	coclass ViewControllerService
	{
		[default] interface IViewControllerService;
	};
	[
		uuid(C4587505-CBA9-4583-A0F0-CA7BEF457FA0)		
	]
	coclass ThemeService
	{
		[default] interface IThemeService;
	};
	[
		uuid(A7C215DD-BB09-4045-9029-9EE9D1D0A389)		
	]
	coclass ThemeDefault
	{
		[default] interface ITheme;
	};
	[
		uuid(B682B92C-ACB3-446D-A37D-E11C901385CA)		
	]
	coclass SkinTimeline
	{
		[default] interface ISkinTimeline;
	};
	[
		uuid(41F33BEE-3D82-4173-9F5E-79C91523843B)		
	]
	coclass ThemeColorMap
	{
		[default] interface IThemeColorMap;
	};
	[
		uuid(986AF532-E457-4A2D-894D-0805AB6BD0B1)
	]
	coclass ThemeFontMap
	{
		[default] interface IThemeFontMap;
	};
	[
		uuid(89CA168E-8568-4653-9DCF-8DEB3CA21A37)		
	]
	coclass ColumnRects
	{
		[default] interface IColumnRects;
	};
	[
		uuid(07E747E2-451F-498F-B460-E46A44C5126C)
	]
	coclass OpenUrlService
	{
		[default] interface IOpenUrlService;
	};
	[
		uuid(F09290A9-AF90-416D-9309-C649ECC97935)
	]
	coclass TimelineControlCopyCommand
	{
		[default] interface ICommand;
	};
};

import "shobjidl.idl";
