// twitter.idl : IDL source for twitter
//

// This file will be processed by the MIDL tool to
// produce the type library (twitter.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "twmdl_contract_i.idl";

[
	uuid(12BF3C97-9ACD-43C3-9E73-698AF2DAE645),
	version(1.0),
]
library twitterLib
{
	importlib("stdole2.tlb");

	[
		uuid(6EA78630-DC6D-4D2B-91F0-686B260F29D6)
	]
	coclass PluginTable
	{
		[default] interface IPluginTable;
	};
    [
        uuid(BB50CFC0-3B7E-47AC-93C9-E3B7A8CD3762)
    ]
    coclass FollowingControlService
    {
        [default] interface IUnknown;
    };
	[
		uuid(A763588D-7894-4A63-B2A1-87CFA15DC421)
	]
	coclass ListsTimelineService
	{
		[default] interface IUnknown;
	};
	[
		uuid(FA34D58E-7EDC-4084-982A-2620979A6D55)
	]
	coclass LoginService
	{
		[default] interface IUnknown;
	};
	[
		uuid(5BEE1835-5D53-48C0-AB58-05EC1513010F)
	]
	coclass FormsService
	{
		[default] interface IFormsService;
	};
	[
		uuid(438C2243-2D84-455D-BE36-BAB54462AB07)
	]
	coclass HomeTimelineControllerService
	{
		[default] interface IHomeTimelineControllerService;
	};
	[
		uuid(A7558E3E-5C3B-44E3-A4CB-C63127AF6445)
	]
	coclass HomeTimelineStreamingService
	{
		[default] interface IUnknown;
	};
	[
		uuid(6E86988C-AD2D-4EC5-B353-582524F03268)
	]
	coclass TimelineQueueService
	{
		[default] interface ITimelineQueueService;
	};
	[
		uuid(E08071C7-127B-4282-BF4B-F701C66526CD)
	]
	coclass TimelineLoadingService
	{
		[default] interface ITimelineLoadingService;
	};
	[
		uuid(FE18BF94-8AB4-4F45-BFDC-2B2E90DD0C05)
	]
	coclass ShowMoreSupportService
	{
		[default] interface ITimelineControlEventSink;
	};
	[
		uuid(FB68EE85-7555-407C-BECA-64406C74F1BC)
	]
	coclass HomeTimelineService
	{
		[default] interface ITimelineService;
	};
	[
		uuid(4563BFAF-AF65-43B3-84BC-619BDA318391)
	]
	coclass UserTimelineService
	{
		[default] interface ITimelineService;
	};
	[
		uuid(A31AF0A5-BE10-46FE-974F-55E0AA68070D)
	]
	coclass ViewControllerService
	{
		[default] interface IViewControllerService;
	};
	[
		uuid(C4587505-CBA9-4583-A0F0-CA7BEF457FA0)
	]
	coclass ThemeService
	{
		[default] interface IThemeService;
	};
	[
		uuid(07E747E2-451F-498F-B460-E46A44C5126C)
	]
	coclass OpenUrlService
	{
		[default] interface IOpenUrlService;
	};
	[
		uuid(8A7C5710-9FCB-4FD9-83A2-36EE81E10FB9)
	]
	coclass DownloadService
	{
		[default] interface IDownloadService;
	};
	[
		uuid(8C2F7C68-A0A4-4A79-9908-5FE3D1596C7A)
	]
	coclass UpdateService
	{
		[default] interface IUpdateService;
	};
	[
		uuid(DD23A3C8-D851-4F92-9201-276ED70C162F)
	]
	coclass WindowService
	{
		[default] interface IWindowService;
	};
	[
		uuid(51856EF3-A8A6-4B84-95E7-84C6B107271C)
	]
	coclass TimelineImageService
	{
		[default] interface ITimelineImageService;
	};
	[
		uuid(ECFFA762-CEF8-430C-8B9F-E6203D228D74)
	]
	coclass TimelineCleanupService
	{
		[default] interface ITimelineCleanupService;
	};
	[
		uuid(51E59535-2665-4C06-B550-3FF56565F89B)
	]
	coclass TabbedControlStatusService
	{
		[default] interface IUnknown;
	};
	[
		uuid(8EA62966-384D-4768-96F9-C8A61B4CDF12)
	]
	coclass TwitViewRepliesService
	{
		[default] interface ITwitViewRepliesService;
	};
	[
		uuid(68590141-7E8A-4993-BF22-77F31E8B888D)
	]
	coclass SearchTimelineService
	{
		[default] interface ISearchTimelineService;
	};
	[
		uuid(29B8920F-970F-4049-AC6C-5DD7ABD9527B)
	]
	coclass TimelineRelativeTimeService
	{
		[default] interface ITimelineRelativeTimeService;
	};
	[
		uuid(951B8635-6514-485A-B31D-3C0293203B79)
	]
	coclass FollowStatusService
	{
		[default] interface IUnknown;
	};
	[
		uuid(B03DDD69-58E8-4582-8908-504D7595B579)
	]
	coclass FollowService
	{
		[default] interface IFollowService;
	};
	[
		uuid(7020C8B1-CCB9-4EDE-B60C-0584580CCB4B)
	]
	coclass ListTimelineControlService
	{
		[default] interface IUnknown;
	};
	[
		uuid(90656AF9-2274-451A-9EF7-5DDFBB7D338F)
	]
	coclass GetUserService
	{
		[default] interface IUnknown;
	};
};

import "shobjidl.idl";
